"""Added user authentication functionality

Revision ID: 1ea1f16d4348
Revises: a93027102b
Create Date: 2015-04-26 19:35:28.509709

"""

# revision identifiers, used by Alembic.
revision = '1ea1f16d4348'
down_revision = 'a93027102b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
