"""User authentication data and customer data

Revision ID: a93027102b
Revises: 559dadefe484
Create Date: 2015-04-26 15:30:35.578614

"""

# revision identifiers, used by Alembic.
revision = 'a93027102b'
down_revision = '559dadefe484'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periods',
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('period')
    )
    op.create_index(op.f('ix_periods_period'), 'periods', ['period'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=900), nullable=True),
    sa.Column('category', sa.String(length=900), nullable=False),
    sa.Column('sub_category', sa.String(length=900), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=900), nullable=False),
    sa.Column('record_type', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('tier', sa.String(length=6), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('credit_name', sa.String(length=600), nullable=False),
    sa.Column('credit_value', sa.Numeric(precision=30, scale=6), nullable=False),
    sa.Column('credit_remaining_value', sa.Numeric(precision=30, scale=6), nullable=False),
    sa.Column('redeemed_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Date(), nullable=True),
    sa.Column('promotion_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('spend', sa.Numeric(precision=30, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['period'], ['periods.period'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'users', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column(u'users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column(u'users', 'password_hash')
    op.drop_column(u'users', 'email')
    op.drop_table('spend')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_periods_period'), table_name='periods')
    op.drop_table('periods')
    ### end Alembic commands ###
